spring.application.name=backend


#spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
#spring.datasource.username=postgres
#spring.datasource.password=Postgre@4722

spring.datasource.url=jdbc:postgresql://dpg-d7u581f7f7vs73em64qg-a.singapore-postgres.render.com:5432/task_manager_s5vf
spring.datasource.username=task_manager_s5vf_user
spring.datasource.password=TemjmmpapxUsDHeqQs4vyDi7Xbs2tMb6
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootApp
logging.level.org.springframework.security=DEBUG